.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/AnimationComponent.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/AnimationComponent.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/Animation\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimationComponent\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
