.TH "Armory" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Armory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Armory\&.hpp>\fP
.PP
Est dérivée de \fBItem\fP\&.
.PP
Dérivée par \fBBoxingGloves\fP, \fBShield\fP, et \fBSword\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBArmory\fP (std::string_view const &imageSpritePath, \fBgame::ItemsCategories\fP \fBcategorie\fP)"
.br
.ti -1c
.RI "\fB~Armory\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB9\fP du fichier \fBArmory\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Armory::Armory (std::string_view const & imageSpritePath, \fBgame::ItemsCategories\fP categorie)"

.PP
Définition à la ligne \fB8\fP du fichier \fBArmory\&.cpp\fP\&.
.SS "Armory::~Armory ()"

.PP
Définition à la ligne \fB13\fP du fichier \fBArmory\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
