.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/Bag.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/Bag.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/NotMovableGameObject\&.hpp'\fP
.br
\fC#include 'include/Inventory\&.hpp'\fP
.br
\fC#include 'include/Item\&.hpp'\fP
.br
\fC#include 'include/consts\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBag\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
