.TH "Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform/Unix" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform/Unix
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBLinuxPlatform\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBLinuxPlatform\&.hpp\fP"
.br
.in -1c
