.TH "Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform/Win32" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform/Win32
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBResource\&.h\fP"
.br
.ti -1c
.RI "fichier \fBWindowsPlatform\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBWindowsPlatform\&.hpp\fP"
.br
.in -1c
