.TH "Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src/Platform
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBMacOS\fP"
.br
.ti -1c
.RI "répertoire \fBUnix\fP"
.br
.ti -1c
.RI "répertoire \fBWin32\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBIPlatform\&.hpp\fP"
.br
.ti -1c
.RI "fichier \fBPlatform\&.hpp\fP"
.br
.in -1c
