.TH "Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/programs_sc/CIC/MITST06/jeu/src
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBinclude\fP"
.br
.ti -1c
.RI "répertoire \fBPlatform\fP"
.br
.ti -1c
.RI "répertoire \fBUtility\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBMain\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBPCH\&.hpp\fP"
.br
.in -1c
