.TH "Druid" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Druid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Druid\&.hpp>\fP
.PP
Est dérivée de \fBPersonage\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDruid\fP ()"
.br
.ti -1c
.RI "\fB~Druid\fP ()"
.br
.ti -1c
.RI "virtual void \fBsimpleAttack\fP (\fBPersonage\fP &target) override"
.br
.ti -1c
.RI "virtual void \fBspecialAttack\fP (\fBPersonage\fP &target) override"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB8\fP du fichier \fBDruid\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Druid::Druid ()"

.PP
Définition à la ligne \fB16\fP du fichier \fBDruid\&.cpp\fP\&.
.SS "Druid::~Druid ()"

.PP
Définition à la ligne \fB21\fP du fichier \fBDruid\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Druid::simpleAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB26\fP du fichier \fBDruid\&.cpp\fP\&.
.SS "void Druid::specialAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB31\fP du fichier \fBDruid\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
