.TH "EnemyData" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemyData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnemyManager\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "bool \fBactive\fP"
.br
.RI "Est vrai si l'énémi se trouve dans la meme salle que le joueur\&. "
.ti -1c
.RI "\fBEnemy\fP * \fBenemy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB11\fP du fichier \fBEnemyManager\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "bool EnemyData::active"

.PP
Est vrai si l'énémi se trouve dans la meme salle que le joueur\&. 
.PP
Définition à la ligne \fB17\fP du fichier \fBEnemyManager\&.hpp\fP\&.
.SS "\fBEnemy\fP* EnemyData::enemy"

.PP
Définition à la ligne \fB18\fP du fichier \fBEnemyManager\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
