.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/EnemyManager.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/EnemyManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/Enemy\&.hpp'\fP
.br
\fC#include 'include/Hall\&.hpp'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEnemyData\fP"
.br
.ti -1c
.RI "class \fBEnemyManager\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
