.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/EnemyManager.cpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/EnemyManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/EnemyManager\&.hpp'\fP
.br
\fC#include 'include/Druid\&.hpp'\fP
.br
\fC#include 'include/Religious\&.hpp'\fP
.br
\fC#include 'include/Soldier\&.hpp'\fP
.br
\fC#include 'include/Worker\&.hpp'\fP
.br
\fC#include 'include/consts\&.hpp'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
