.TH "game::ItemActionResult" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game::ItemActionResult \- Resultat retourné à l'utilisateur après une l'utilisation d'un item sur un personage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <consts\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "short int \fBhealthDecrease\fP"
.br
.RI "Valeur de qanté diminué "
.ti -1c
.RI "short int \fBexperienceDecrease\fP"
.br
.RI "Valeur de l'expérience diminué "
.ti -1c
.RI "short int \fBhealthIncrease\fP"
.br
.RI "Valeur de qanté Augmenté "
.ti -1c
.RI "short int \fBexperienceincrease\fP"
.br
.RI "Valeur de l'expérience Augmenté "
.ti -1c
.RI "bool \fBisDied\fP"
.br
.RI "Le personage attaqué est mort? "
.in -1c
.SH "Description détaillée"
.PP 
Resultat retourné à l'utilisateur après une l'utilisation d'un item sur un personage\&. 
.PP
Définition à la ligne \fB135\fP du fichier \fBconsts\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "short int game::ItemActionResult::experienceDecrease"

.PP
Valeur de l'expérience diminué 
.PP
Définition à la ligne \fB146\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "short int game::ItemActionResult::experienceincrease"

.PP
Valeur de l'expérience Augmenté 
.PP
Définition à la ligne \fB156\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "short int game::ItemActionResult::healthDecrease"

.PP
Valeur de qanté diminué 
.PP
Définition à la ligne \fB141\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "short int game::ItemActionResult::healthIncrease"

.PP
Valeur de qanté Augmenté 
.PP
Définition à la ligne \fB151\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "bool game::ItemActionResult::isDied"

.PP
Le personage attaqué est mort? 
.PP
Définition à la ligne \fB161\fP du fichier \fBconsts\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
