.TH "game::PlayerStats" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game::PlayerStats
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <consts\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned \fBscore\fP"
.br
.ti -1c
.RI "unsigned \fBenemyKilled\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB164\fP du fichier \fBconsts\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned game::PlayerStats::enemyKilled"

.PP
Définition à la ligne \fB167\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "unsigned game::PlayerStats::score"

.PP
Définition à la ligne \fB166\fP du fichier \fBconsts\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
