.TH "GameMaster" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameMaster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameMaster\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBGameMaster\fP ()"
.br
.ti -1c
.RI "\fB~GameMaster\fP ()"
.br
.ti -1c
.RI "void \fBendApplication\fP ()"
.br
.ti -1c
.RI "void \fBupdateDeltatime\fP ()"
.br
.ti -1c
.RI "void \fBupdateSFMLEvents\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static const \fBGameMaster\fP * \fBGAME_MASTER\fP ()"
.br
.ti -1c
.RI "static \fBStateData\fP * \fBSTATE_DATA\fP ()"
.br
.ti -1c
.RI "static const sf::Vector2i \fBgetSPRITE_BOX_CENTER\fP ()"
.br
.ti -1c
.RI "static float \fBgetSCREEN_SCALING_FACTOR\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB16\fP du fichier \fBGameMaster\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "GameMaster::GameMaster ()"

.PP
Définition à la ligne \fB145\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "GameMaster::~GameMaster ()"

.PP
Définition à la ligne \fB162\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void GameMaster::endApplication ()"

.PP
Définition à la ligne \fB199\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "const \fBGameMaster\fP * GameMaster::GAME_MASTER ()\fC [static]\fP"

.PP
Définition à la ligne \fB183\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "float GameMaster::getSCREEN_SCALING_FACTOR ()\fC [static]\fP"

.PP
Définition à la ligne \fB193\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "const sf::Vector2i GameMaster::getSPRITE_BOX_CENTER ()\fC [static]\fP"

.PP
Définition à la ligne \fB178\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "void GameMaster::render ()"

.PP
Définition à la ligne \fB257\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "void GameMaster::run ()"

.PP
Définition à la ligne \fB289\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "\fBStateData\fP * GameMaster::STATE_DATA ()\fC [static]\fP"

.PP
Définition à la ligne \fB188\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "void GameMaster::update ()"

.PP
Définition à la ligne \fB233\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "void GameMaster::updateDeltatime ()"

.PP
Définition à la ligne \fB204\fP du fichier \fBGameMaster\&.cpp\fP\&.
.SS "void GameMaster::updateSFMLEvents ()"

.PP
Définition à la ligne \fB211\fP du fichier \fBGameMaster\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
