.TH "game::AttackSateInformations" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game::AttackSateInformations
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <consts\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "float \fBwaitingForActionToOtherPersonageEnd\fP"
.br
.RI "Le temps d'attente pour que l'ataque soit éffective\&. C'est après cette attente qu'on envois les dégats\&. "
.ti -1c
.RI "bool \fBattacking\fP"
.br
.ti -1c
.RI "\fBgame::ItemsCategories\fP \fBitemCategorie\fP"
.br
.ti -1c
.RI "short int \fBside\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB117\fP du fichier \fBconsts\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "bool game::AttackSateInformations::attacking"

.PP
Définition à la ligne \fB125\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "\fBgame::ItemsCategories\fP game::AttackSateInformations::itemCategorie"

.PP
Définition à la ligne \fB126\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "short int game::AttackSateInformations::side"

.PP
Définition à la ligne \fB128\fP du fichier \fBconsts\&.hpp\fP\&.
.SS "float game::AttackSateInformations::waitingForActionToOtherPersonageEnd"

.PP
Le temps d'attente pour que l'ataque soit éffective\&. C'est après cette attente qu'on envois les dégats\&. 
.PP
Définition à la ligne \fB124\fP du fichier \fBconsts\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
