.TH "gui" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButton\fP"
.br
.ti -1c
.RI "class \fBInventory\fP"
.br
.ti -1c
.RI "class \fBInventoryButton\fP"
.br
.ti -1c
.RI "class \fBProgressBar\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "float \fBp2pX\fP (const float perc, const sf::VideoMode &vm)"
.br
.ti -1c
.RI "float \fBp2pY\fP (const float perc, const sf::VideoMode &vm)"
.br
.ti -1c
.RI "unsigned \fBcalcCharSize\fP (const sf::VideoMode &vm, const unsigned modifier=60)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "unsigned gui::calcCharSize (const sf::VideoMode & vm, const unsigned modifier = \fC60\fP)"

.PP
Définition à la ligne \fB37\fP du fichier \fBGui\&.cpp\fP\&.
.SS "float gui::p2pX (const float perc, const sf::VideoMode & vm)"

.PP
Définition à la ligne \fB9\fP du fichier \fBGui\&.cpp\fP\&.
.SS "float gui::p2pY (const float perc, const sf::VideoMode & vm)"

.PP
Définition à la ligne \fB23\fP du fichier \fBGui\&.cpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
