.TH "gui::InventoryItemData" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui::InventoryItemData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gui\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "const \fBItem\fP * \fBitem\fP"
.br
.ti -1c
.RI "const short \fBIndex\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB170\fP du fichier \fBGui\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "const short gui::InventoryItemData::Index"

.PP
Définition à la ligne \fB173\fP du fichier \fBGui\&.hpp\fP\&.
.SS "const \fBItem\fP* gui::InventoryItemData::item"

.PP
Définition à la ligne \fB172\fP du fichier \fBGui\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
