.TH "Hall" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hall
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hall\&.hpp>\fP
.PP
Dérivée par \fBLounge\fP, et \fBRoom\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHall\fP (sf::Vector2i topLeftPoint, int width, int height)"
.br
.ti -1c
.RI "virtual \fB~Hall\fP ()"
.br
.ti -1c
.RI "virtual bool \fBaddMovableGameObject\fP (\fBMovableGameObject\fP *movableGameObject)"
.br
.ti -1c
.RI "bool \fBisIn\fP (\fBMyVector\fP const &coordinates) const"
.br
.ti -1c
.RI "bool \fBisIn\fP (sf::Vector2f const &coordinates) const"
.br
.ti -1c
.RI "const sf::IntRect & \fBgetIntRect\fP () const"
.br
.ti -1c
.RI "virtual void \fBrender\fP (sf::RenderTarget &target)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB11\fP du fichier \fBHall\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Hall::Hall (sf::Vector2i topLeftPoint, int width, int height)"

.PP
Définition à la ligne \fB8\fP du fichier \fBHall\&.cpp\fP\&.
.SS "Hall::~Hall ()\fC [virtual]\fP"

.PP
Définition à la ligne \fB24\fP du fichier \fBHall\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "bool Hall::addMovableGameObject (\fBMovableGameObject\fP * movableGameObject)\fC [virtual]\fP"

.PP
Définition à la ligne \fB29\fP du fichier \fBHall\&.cpp\fP\&.
.SS "const sf::IntRect & Hall::getIntRect () const"

.PP
Définition à la ligne \fB60\fP du fichier \fBHall\&.cpp\fP\&.
.SS "bool Hall::isIn (\fBMyVector\fP const & coordinates) const"

.PP
Définition à la ligne \fB35\fP du fichier \fBHall\&.cpp\fP\&.
.SS "bool Hall::isIn (sf::Vector2f const & coordinates) const"

.PP
Définition à la ligne \fB47\fP du fichier \fBHall\&.cpp\fP\&.
.SS "void Hall::render (sf::RenderTarget & target)\fC [virtual]\fP"

.PP
Définition à la ligne \fB65\fP du fichier \fBHall\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
