.TH "House" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
House
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <House\&.hpp>\fP
.PP
Est dérivée de \fBGameMap\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHouse\fP ()"
.br
.ti -1c
.RI "\fB~House\fP ()"
.br
.ti -1c
.RI "virtual const int * \fBgetDisposition\fP () const override"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB7\fP du fichier \fBHouse\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "House::House ()"

.PP
Définition à la ligne \fB7\fP du fichier \fBHouse\&.cpp\fP\&.
.SS "House::~House ()"

.PP
Définition à la ligne \fB3292\fP du fichier \fBHouse\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "const int * House::getDisposition () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBGameMap\fP\&.
.PP
Définition à la ligne \fB3298\fP du fichier \fBHouse\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
