.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/Item.hpp" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/Item.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/NotMovableGameObject\&.hpp'\fP
.br
\fC#include 'include/Personage\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.RI "Représente éssentiellement les object que pourra manipuler les personnages\&. "
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum class \fBItemsCategories\fP { \fBMONEY\fP, \fBTELEPORTKEY\fP, \fBDEFEND\fP, \fBATTACK_BODY_TO_BODY\fP, \fBATTACK_DISTANCE\fP, \fBVIAL_EXP\fP, \fBVIAL_HEALTH\fP, \fBVIAL_ATTACK_EXP\fP, \fBVIAL_ATTACK_HEALTH\fP }"
.br
.RI "Représente les catégories d'items\&. TODO - Compléter\&.\&.\&.\&. Va surtout aider dans l'utilisation de l'item et son comportement\&. "
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum class \fBItemsCategories\fP\fC [strong]\fP"

.PP
Représente les catégories d'items\&. TODO - Compléter\&.\&.\&.\&. Va surtout aider dans l'utilisation de l'item et son comportement\&. 
.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIMONEY \fP\fP
.TP
\fB\fITELEPORTKEY \fP\fP
.TP
\fB\fIDEFEND \fP\fP
.TP
\fB\fIATTACK_BODY_TO_BODY \fP\fP
.TP
\fB\fIATTACK_DISTANCE \fP\fP
.TP
\fB\fIVIAL_EXP \fP\fP
.TP
\fB\fIVIAL_HEALTH \fP\fP
.TP
\fB\fIVIAL_ATTACK_EXP \fP\fP
.TP
\fB\fIVIAL_ATTACK_HEALTH \fP\fP
.PP
Définition à la ligne \fB15\fP du fichier \fBItem\&.hpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
