.TH "Item" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Item \- Représente éssentiellement les object que pourra manipuler les personnages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Item\&.hpp>\fP
.PP
Est dérivée de \fBNotMovableGameObject\fP\&.
.PP
Dérivée par \fBArmory\fP, \fBMoney\fP, \fBTeleportKey\fP, et \fBVial\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBItem\fP (std::string_view const &imageSpritePath, \fBgame::ItemsCategories\fP \fBcategorie\fP)"
.br
.ti -1c
.RI "\fB~Item\fP ()"
.br
.ti -1c
.RI "\fBgame::ItemsCategories\fP const & \fBgetCategorie\fP () const"
.br
.RI "Get the Categorie object\&. "
.ti -1c
.RI "virtual void \fBonCollisionEnter\fP (\fBCollision\fP const &collision) const =0"
.br
.RI "émit quand il entre en contacte avec un autre élément "
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.ti -1c
.RI "unsigned const & \fBgetValue\fP () const"
.br
.RI "Returne la valeur de l'effet de cet arme\&. "
.ti -1c
.RI "float const & \fBgetRangeOfAction\fP () const"
.br
.RI "Retourne le rayon d'action de l'item\&. "
.ti -1c
.RI "float const & \fBgetWaitingTimeForAction\fP () const"
.br
.RI "Retourne le temps d'attente pour que l'action soit faite\&. "
.ti -1c
.RI "bool const & \fBisOneUse\fP () const"
.br
.RI "Indique si l'item est à usage unique\&. "
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "virtual void \fBupdatePosition\fP (float posX, float posY)=0"
.br
.RI "Permet de mettre à jour la position actuelle\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "unsigned \fBvalue\fP"
.br
.RI "Valeur de l'item à l'utilisation\&.\&.\&. "
.ti -1c
.RI "float \fBrangeOfAction\fP"
.br
.RI "rayon d'action de l'item "
.ti -1c
.RI "float \fBwaitingTimeForAction\fP"
.br
.RI "Le temps d'attente pour que l'action soit faite\&. "
.ti -1c
.RI "const \fBgame::ItemsCategories\fP \fBcategorie\fP"
.br
.RI "Représente les categories d'item\&. utilis pour définir les éffets\&.\&.\&. "
.ti -1c
.RI "bool \fBoneUse\fP"
.br
.RI "Indique si l'item ne peut etre utilisé qu'une seule fois\&. "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Représente éssentiellement les object que pourra manipuler les personnages\&. 
.PP
Définition à la ligne \fB22\fP du fichier \fBItem\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Item::Item (std::string_view const & imageSpritePath, \fBgame::ItemsCategories\fP categorie)"

.PP
Définition à la ligne \fB8\fP du fichier \fBItem\&.cpp\fP\&.
.SS "Item::~Item ()"

.PP
Définition à la ligne \fB18\fP du fichier \fBItem\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBgame::ItemsCategories\fP const  & Item::getCategorie () const"

.PP
Get the Categorie object\&. 
.PP
\fBRenvoie\fP
.RS 4
\fBgame::ItemsCategories\fP& 
.RE
.PP

.PP
Définition à la ligne \fB22\fP du fichier \fBItem\&.cpp\fP\&.
.SS "float const  & Item::getRangeOfAction () const"

.PP
Retourne le rayon d'action de l'item\&. 
.PP
\fBRenvoie\fP
.RS 4
float const& 
.RE
.PP

.PP
Définition à la ligne \fB32\fP du fichier \fBItem\&.cpp\fP\&.
.SS "unsigned const  & Item::getValue () const"

.PP
Returne la valeur de l'effet de cet arme\&. 
.PP
\fBRenvoie\fP
.RS 4
unsigned const& 
.RE
.PP

.PP
Définition à la ligne \fB27\fP du fichier \fBItem\&.cpp\fP\&.
.SS "float const  & Item::getWaitingTimeForAction () const"

.PP
Retourne le temps d'attente pour que l'action soit faite\&. 
.PP
\fBRenvoie\fP
.RS 4
float const& 
.RE
.PP

.PP
Définition à la ligne \fB37\fP du fichier \fBItem\&.cpp\fP\&.
.SS "bool const  & Item::isOneUse () const"

.PP
Indique si l'item est à usage unique\&. 
.PP
\fBRenvoie\fP
.RS 4
true 
.PP
false 
.RE
.PP

.PP
Définition à la ligne \fB42\fP du fichier \fBItem\&.cpp\fP\&.
.SS "virtual void Item::onCollisionEnter (\fBCollision\fP const & collision) const\fC [pure virtual]\fP"

.PP
émit quand il entre en contacte avec un autre élément 
.PP
\fBParamètres\fP
.RS 4
\fIcollision\fP 
.RE
.PP

.PP
Implémente \fBNotMovableGameObject\fP\&.
.PP
Implémenté dans \fBBoxingGloves\fP, \fBMoney\fP, \fBShield\fP, \fBSword\fP, \fBTeleportKey\fP, et \fBVial\fP\&.
.SS "virtual void Item::update ()\fC [pure virtual]\fP"

.PP
Implémente \fBNotMovableGameObject\fP\&.
.PP
Implémenté dans \fBBoxingGloves\fP, \fBMoney\fP, \fBShield\fP, \fBSword\fP, \fBTeleportKey\fP, et \fBVial\fP\&.
.SS "virtual void Item::updatePosition (float posX, float posY)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Permet de mettre à jour la position actuelle\&. 
.PP
Implémente \fBNotMovableGameObject\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "const \fBgame::ItemsCategories\fP Item::categorie\fC [protected]\fP"

.PP
Représente les categories d'item\&. utilis pour définir les éffets\&.\&.\&. 
.PP
Définition à la ligne \fB100\fP du fichier \fBItem\&.hpp\fP\&.
.SS "bool Item::oneUse\fC [protected]\fP"

.PP
Indique si l'item ne peut etre utilisé qu'une seule fois\&. 
.PP
Définition à la ligne \fB105\fP du fichier \fBItem\&.hpp\fP\&.
.SS "float Item::rangeOfAction\fC [protected]\fP"

.PP
rayon d'action de l'item 
.PP
Définition à la ligne \fB89\fP du fichier \fBItem\&.hpp\fP\&.
.SS "unsigned Item::value\fC [protected]\fP"

.PP
Valeur de l'item à l'utilisation\&.\&.\&. 
.PP
Définition à la ligne \fB84\fP du fichier \fBItem\&.hpp\fP\&.
.SS "float Item::waitingTimeForAction\fC [protected]\fP"

.PP
Le temps d'attente pour que l'action soit faite\&. 
.PP
Définition à la ligne \fB94\fP du fichier \fBItem\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
