.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/Item.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/Item.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/Personage\&.hpp'\fP
.br
\fC#include 'include/consts\&.hpp'\fP
.br
\fC#include 'include/Collision\&.hpp'\fP
.br
\fC#include 'include/NotMovableGameObject\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.RI "Représente éssentiellement les object que pourra manipuler les personnages\&. "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBgame\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
