.TH "Lounge" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lounge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lounge\&.hpp>\fP
.PP
Est dérivée de \fBHall\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBLounge\fP (sf::Vector2i topLeftPoint, int width, int height)"
.br
.ti -1c
.RI "\fB~Lounge\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBLounge\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Lounge::Lounge (sf::Vector2i topLeftPoint, int width, int height)"

.PP
Définition à la ligne \fB8\fP du fichier \fBLounge\&.cpp\fP\&.
.SS "Lounge::~Lounge ()"

.PP
Définition à la ligne \fB13\fP du fichier \fBLounge\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
