.TH "C:/programs_sc/CIC/MITST06/jeu/src/Platform/MacOS/MacOSPlatform.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/Platform/MacOS/MacOSPlatform.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Platform/IPlatform\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fButil::MacOSPlatform\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
