.TH "C:/programs_sc/CIC/MITST06/jeu/src/Main.cpp" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/Main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Platform/Platform\&.hpp'\fP
.br
\fC#include 'include/GameMaster\&.hpp'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main ()"

.PP
Définition à la ligne \fB4\fP du fichier \fBMain\&.cpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
