.TH "Maison" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maison
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Test\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMaison\fP ()"
.br
.ti -1c
.RI "\fB~Maison\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBTest\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Maison::Maison ()"

.PP
Définition à la ligne \fB3\fP du fichier \fBTest\&.cpp\fP\&.
.SS "Maison::~Maison ()"

.PP
Définition à la ligne \fB3300\fP du fichier \fBTest\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Maison::update ()"

.PP
Définition à la ligne \fB3306\fP du fichier \fBTest\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
