.TH "MovableGameObject" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovableGameObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MovableGameObject\&.hpp>\fP
.PP
Est dérivée de \fBGameObject\fP\&.
.PP
Dérivée par \fBPersonage\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMovableGameObject\fP (std::string_view const &imageSpritePath)"
.br
.ti -1c
.RI "\fB~MovableGameObject\fP ()"
.br
.ti -1c
.RI "virtual void \fBmove\fP (\fBMyVector\fP &speed)=0"
.br
.ti -1c
.RI "\fBAnimationComponent\fP * \fBgetAnimationComponent\fP ()"
.br
.ti -1c
.RI "virtual bool \fBaddToHall\fP (\fBHall\fP *\fBhall\fP)"
.br
.RI "Déplacer un objet vers une salle est virtuel pour permettre de récrire la fonction et spécifier peut être des conditions de déplacement\&. NOTE - Cet déplacement ne concerne pas le chagement des cordonnes mais juste l'éta d'appartenance\&. Néanmoins c'est à partir d'elle qu'on informe l'object des nouvelles limites de mouvement\&. "
.ti -1c
.RI "virtual const \fBHall\fP * \fBgetActualHall\fP () const"
.br
.RI "Get the Actual \fBHall\fP object\&. "
.ti -1c
.RI "virtual void \fBshow\fP (sf::RenderTarget &window)"
.br
.RI "Pour dessiner l'élement dans la fenêtre\&. "
.ti -1c
.RI "virtual void \fBonCollisionEnter\fP (\fBCollision\fP const &collision) const =0"
.br
.RI "émit quand il entre en contacte avec un autre élément "
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBcreateAnimationComponent\fP (sf::Texture &texture)"
.br
.ti -1c
.RI "virtual void \fBinitPosition\fP (float posX, float posY) override"
.br
.ti -1c
.RI "virtual void \fBinitAnimations\fP ()=0"
.br
.RI "Initialiser animationComponent et les animations\&. "
.ti -1c
.RI "virtual void \fBsetPositionMovementLimit\fP (const \fBHall\fP *\fBhall\fP)"
.br
.RI "Met à jour les nouvelle limite de déplacement\&. "
.ti -1c
.RI "virtual void \fBupdatePosition\fP (float posX, float posY)=0"
.br
.RI "Permet de mettre à jour la position actuelle\&. "
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBAnimationComponent\fP * \fBanimationComponent\fP"
.br
.ti -1c
.RI "const \fBHall\fP * \fBhall\fP"
.br
.RI "Ce pointeur ne doit pas être supprimé à ce niveau\&. "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB17\fP du fichier \fBMovableGameObject\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MovableGameObject::MovableGameObject (std::string_view const & imageSpritePath)"

.PP
Définition à la ligne \fB13\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "MovableGameObject::~MovableGameObject ()"

.PP
Définition à la ligne \fB19\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "bool MovableGameObject::addToHall (\fBHall\fP * hall)\fC [virtual]\fP"

.PP
Déplacer un objet vers une salle est virtuel pour permettre de récrire la fonction et spécifier peut être des conditions de déplacement\&. NOTE - Cet déplacement ne concerne pas le chagement des cordonnes mais juste l'éta d'appartenance\&. Néanmoins c'est à partir d'elle qu'on informe l'object des nouvelles limites de mouvement\&. 
.PP
\fBParamètres\fP
.RS 4
\fIhall\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
true Si le déplacement s'est effectué avec succès 
.PP
false Si le déplacement n'a pas eu lieu 
.RE
.PP

.PP
Définition à la ligne \fB37\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "void MovableGameObject::createAnimationComponent (sf::Texture & texture)\fC [protected]\fP"

.PP
Définition à la ligne \fB27\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "const \fBHall\fP * MovableGameObject::getActualHall () const\fC [virtual]\fP"

.PP
Get the Actual \fBHall\fP object\&. 
.PP
\fBRenvoie\fP
.RS 4
const Hall* 
.RE
.PP

.PP
Définition à la ligne \fB44\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "\fBAnimationComponent\fP * MovableGameObject::getAnimationComponent ()"

.PP
Définition à la ligne \fB32\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "virtual void MovableGameObject::initAnimations ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Initialiser animationComponent et les animations\&. 
.PP
Implémenté dans \fBPersonage\fP\&.
.SS "void MovableGameObject::initPosition (float posX, float posY)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implémente \fBGameObject\fP\&.
.PP
Définition à la ligne \fB6\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "virtual void MovableGameObject::move (\fBMyVector\fP & speed)\fC [pure virtual]\fP"

.PP
Implémenté dans \fBPersonage\fP\&.
.SS "virtual void MovableGameObject::onCollisionEnter (\fBCollision\fP const & collision) const\fC [pure virtual]\fP"

.PP
émit quand il entre en contacte avec un autre élément 
.PP
\fBParamètres\fP
.RS 4
\fIcollision\fP 
.RE
.PP

.PP
Implémente \fBGameObject\fP\&.
.PP
Implémenté dans \fBPersonage\fP\&.
.SS "void MovableGameObject::setPositionMovementLimit (const \fBHall\fP * hall)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Met à jour les nouvelle limite de déplacement\&. 
.PP
\fBParamètres\fP
.RS 4
\fIhall\fP 
.RE
.PP

.PP
Définition à la ligne \fB54\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "void MovableGameObject::show (sf::RenderTarget & window)\fC [virtual]\fP"

.PP
Pour dessiner l'élement dans la fenêtre\&. 
.PP
\fBParamètres\fP
.RS 4
\fIwindow\fP 
.RE
.PP

.PP
Réimplémentée à partir de \fBGameObject\fP\&.
.PP
Réimplémentée dans \fBPersonage\fP\&.
.PP
Définition à la ligne \fB49\fP du fichier \fBMovableGameObject\&.cpp\fP\&.
.SS "virtual void MovableGameObject::update ()\fC [pure virtual]\fP"

.PP
Implémente \fBGameObject\fP\&.
.PP
Implémenté dans \fBPersonage\fP\&.
.SS "virtual void MovableGameObject::updatePosition (float posX, float posY)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Permet de mettre à jour la position actuelle\&. 
.PP
Implémenté dans \fBPersonage\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBAnimationComponent\fP* MovableGameObject::animationComponent\fC [protected]\fP"

.PP
Définition à la ligne \fB61\fP du fichier \fBMovableGameObject\&.hpp\fP\&.
.SS "const \fBHall\fP* MovableGameObject::hall\fC [protected]\fP"

.PP
Ce pointeur ne doit pas être supprimé à ce niveau\&. 
.PP
Définition à la ligne \fB65\fP du fichier \fBMovableGameObject\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
