.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/MyVector.hpp" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/MyVector.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/consts\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMyVector\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_PI\fP   3\&.14159265358979323846"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define M_PI   3\&.14159265358979323846"

.PP
Définition à la ligne \fB6\fP du fichier \fBMyVector\&.hpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
