.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/NotMovableGameObject.hpp" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/NotMovableGameObject.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/GameObject\&.hpp'\fP
.br
\fC#include 'include/AnimationComponent\&.hpp'\fP
.br
\fC#include 'include/Hall\&.hpp'\fP
.br
\fC#include 'include/Position\&.hpp'\fP
.br
\fC#include 'include/MyVector\&.hpp'\fP
.br
\fC#include 'include/Collision\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNotMovableGameObject\fP"
.br
.RI "Represente les objets imobiles\&. NOTE - Certains de ces Object Peuvent être déplacée ou transporté par un Personnage par exemple\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
