.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/Personage.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/Personage.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/Bag\&.hpp'\fP
.br
\fC#include 'include/Collision\&.hpp'\fP
.br
\fC#include 'include/Gui\&.hpp'\fP
.br
\fC#include 'include/Inventory\&.hpp'\fP
.br
\fC#include 'include/Item\&.hpp'\fP
.br
\fC#include 'include/MovableGameObject\&.hpp'\fP
.br
\fC#include 'include/consts\&.hpp'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPersonage\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBgui\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
