.TH "PolygonCollider" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PolygonCollider
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PolygonCollider\&.hpp>\fP
.PP
Est dérivée de \fBCollider\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPolygonCollider\fP (\fBGameObject\fP const &\fBparent\fP, std::vector< sf::Vector2f > contactPoints)"
.br
.ti -1c
.RI "\fB~PolygonCollider\fP ()"
.br
.ti -1c
.RI "std::vector< sf::Vector2f > \fBgetContactPoints\fP () const override"
.br
.ti -1c
.RI "bool \fBtouchEachOther\fP (\fBCollider\fP const &collider) const override"
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static const std::string \fBgetName\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBPolygonCollider\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "PolygonCollider::PolygonCollider (\fBGameObject\fP const & parent, std::vector< sf::Vector2f > contactPoints)\fC [explicit]\fP"

.PP
Définition à la ligne \fB14\fP du fichier \fBPolygonCollider\&.cpp\fP\&.
.SS "PolygonCollider::~PolygonCollider ()"

.PP
Définition à la ligne \fB19\fP du fichier \fBPolygonCollider\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "std::vector< sf::Vector2f > PolygonCollider::getContactPoints () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBCollider\fP\&.
.PP
Définition à la ligne \fB29\fP du fichier \fBPolygonCollider\&.cpp\fP\&.
.SS "const std::string PolygonCollider::getName ()\fC [static]\fP"

.PP
Définition à la ligne \fB24\fP du fichier \fBPolygonCollider\&.cpp\fP\&.
.SS "bool PolygonCollider::touchEachOther (\fBCollider\fP const & collider) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBCollider\fP\&.
.PP
Définition à la ligne \fB34\fP du fichier \fBPolygonCollider\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
