.TH "Religious" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Religious
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Religious\&.hpp>\fP
.PP
Est dérivée de \fBPersonage\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBReligious\fP ()"
.br
.ti -1c
.RI "\fB~Religious\fP ()"
.br
.ti -1c
.RI "virtual void \fBsimpleAttack\fP (\fBPersonage\fP &target) override"
.br
.ti -1c
.RI "virtual void \fBspecialAttack\fP (\fBPersonage\fP &target) override"
.br
.ti -1c
.RI "virtual unsigned \fBreceiveHealthDamage\fP (int value) override"
.br
.RI "pour recevoir les dégats de santé Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) "
.ti -1c
.RI "virtual unsigned \fBreceiveExpDamage\fP (int value) override"
.br
.RI "pour recevoir les dégats d'exp Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) "
.ti -1c
.RI "virtual unsigned \fBreceiveHealthCare\fP (int value) override"
.br
.RI "pour recevoir les soins santé Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) "
.ti -1c
.RI "virtual unsigned \fBreceiveExpCare\fP (int value) override"
.br
.RI "pour recevoir les soins Exp Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBReligious\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Religious::Religious ()"

.PP
Définition à la ligne \fB15\fP du fichier \fBReligious\&.cpp\fP\&.
.SS "Religious::~Religious ()"

.PP
Définition à la ligne \fB20\fP du fichier \fBReligious\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "unsigned Religious::receiveExpCare (int value)\fC [override]\fP, \fC [virtual]\fP"

.PP
pour recevoir les soins Exp Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) 
.PP
\fBParamètres\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
unsigned 
.RE
.PP

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB32\fP du fichier \fBReligious\&.cpp\fP\&.
.SS "unsigned Religious::receiveExpDamage (int value)\fC [override]\fP, \fC [virtual]\fP"

.PP
pour recevoir les dégats d'exp Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) 
.PP
\fBParamètres\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
unsigned 
.RE
.PP

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB28\fP du fichier \fBReligious\&.cpp\fP\&.
.SS "unsigned Religious::receiveHealthCare (int value)\fC [override]\fP, \fC [virtual]\fP"

.PP
pour recevoir les soins santé Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) 
.PP
\fBParamètres\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
unsigned 
.RE
.PP

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB30\fP du fichier \fBReligious\&.cpp\fP\&.
.SS "unsigned Religious::receiveHealthDamage (int value)\fC [override]\fP, \fC [virtual]\fP"

.PP
pour recevoir les dégats de santé Retourne les dégats réelemnt concidéré (au cas ou la personne utilise un bouclié ou\&.\&.\&.) 
.PP
\fBParamètres\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
unsigned 
.RE
.PP

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB26\fP du fichier \fBReligious\&.cpp\fP\&.
.SS "virtual void Religious::simpleAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBPersonage\fP\&.
.SS "virtual void Religious::specialAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBPersonage\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
