.TH "C:/programs_sc/CIC/MITST06/jeu/src/Platform/Win32/Resource.h" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/Platform/Win32/Resource.h
.SH SYNOPSIS
.br
.PP
\fC#include <winuser\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_ICON_MAIN\fP   1"
.br
.ti -1c
.RI "#define \fBMANIFEST_RESOURCE_ID\fP   1"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define MANIFEST_RESOURCE_ID   1"

.PP
Définition à la ligne \fB7\fP du fichier \fBResource\&.h\fP\&.
.SS "#define WIN32_ICON_MAIN   1"

.PP
Définition à la ligne \fB6\fP du fichier \fBResource\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
