.TH "Rigidbody" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rigidbody
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rigidbody\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBRigidbody\fP (\fBGameObject\fP &parent)"
.br
.ti -1c
.RI "\fB~Rigidbody\fP ()"
.br
.ti -1c
.RI "void \fBonAnotherRigidBodyDetection\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBGameObject\fP & \fBm_parent\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB9\fP du fichier \fBRigidbody\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Rigidbody::Rigidbody (\fBGameObject\fP & parent)"

.PP
Définition à la ligne \fB5\fP du fichier \fBRigidbody\&.cpp\fP\&.
.SS "Rigidbody::~Rigidbody ()"

.PP
Définition à la ligne \fB10\fP du fichier \fBRigidbody\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Rigidbody::onAnotherRigidBodyDetection ()"

.PP
Définition à la ligne \fB14\fP du fichier \fBRigidbody\&.cpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBGameObject\fP& Rigidbody::m_parent\fC [protected]\fP"

.PP
Définition à la ligne \fB18\fP du fichier \fBRigidbody\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
