.TH "Room" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Room
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Room\&.hpp>\fP
.PP
Est dérivée de \fBHall\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBRoom\fP (sf::Vector2i topLeftPoint, int width, int height)"
.br
.ti -1c
.RI "\fB~Room\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBRoom\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Room::Room (sf::Vector2i topLeftPoint, int width, int height)"

.PP
Définition à la ligne \fB7\fP du fichier \fBRoom\&.cpp\fP\&.
.SS "Room::~Room ()"

.PP
Définition à la ligne \fB12\fP du fichier \fBRoom\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
