.TH "Soldier" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Soldier
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Soldier\&.hpp>\fP
.PP
Est dérivée de \fBPersonage\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSoldier\fP (bool isPlayer=false)"
.br
.ti -1c
.RI "\fB~Soldier\fP ()"
.br
.ti -1c
.RI "virtual void \fBsimpleAttack\fP (\fBPersonage\fP &target) override"
.br
.RI "Pour dessiner l'élement dans la fenêtre\&. "
.ti -1c
.RI "virtual void \fBspecialAttack\fP (\fBPersonage\fP &target) override"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB6\fP du fichier \fBSoldier\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Soldier::Soldier (bool isPlayer = \fCfalse\fP)\fC [explicit]\fP"

.PP
Définition à la ligne \fB12\fP du fichier \fBSoldier\&.cpp\fP\&.
.SS "Soldier::~Soldier ()"

.PP
Définition à la ligne \fB18\fP du fichier \fBSoldier\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Soldier::simpleAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Pour dessiner l'élement dans la fenêtre\&. 
.PP
\fBParamètres\fP
.RS 4
\fIwindow\fP 
.RE
.PP

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB24\fP du fichier \fBSoldier\&.cpp\fP\&.
.SS "void Soldier::specialAttack (\fBPersonage\fP & target)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBPersonage\fP\&.
.PP
Définition à la ligne \fB28\fP du fichier \fBSoldier\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
