.TH "StateData" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <State\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "float \fBgridSize\fP"
.br
.ti -1c
.RI "sf::RenderWindow * \fBwindow\fP"
.br
.ti -1c
.RI "\fBGraphicsSettings\fP * \fBgraphicsSettings\fP"
.br
.ti -1c
.RI "std::stack< \fBState\fP * > * \fBstates\fP"
.br
.ti -1c
.RI "sf::Font \fBdefaultFont\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB25\fP du fichier \fBState\&.hpp\fP\&.
.SH "Documentation des données membres"
.PP 
.SS "sf::Font StateData::defaultFont"

.PP
Définition à la ligne \fB33\fP du fichier \fBState\&.hpp\fP\&.
.SS "\fBGraphicsSettings\fP* StateData::graphicsSettings"

.PP
Définition à la ligne \fB29\fP du fichier \fBState\&.hpp\fP\&.
.SS "float StateData::gridSize"

.PP
Définition à la ligne \fB27\fP du fichier \fBState\&.hpp\fP\&.
.SS "std::stack<\fBState\fP*>* StateData::states"

.PP
Définition à la ligne \fB31\fP du fichier \fBState\&.hpp\fP\&.
.SS "sf::RenderWindow* StateData::window"

.PP
Définition à la ligne \fB28\fP du fichier \fBState\&.hpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
