.TH "TeleportKey" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TeleportKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TeleportKey\&.hpp>\fP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBTeleportKey\fP ()"
.br
.ti -1c
.RI "\fB~TeleportKey\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB8\fP du fichier \fBTeleportKey\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "TeleportKey::TeleportKey ()"

.PP
Définition à la ligne \fB8\fP du fichier \fBTeleportKey\&.cpp\fP\&.
.SS "TeleportKey::~TeleportKey ()"

.PP
Définition à la ligne \fB13\fP du fichier \fBTeleportKey\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
