.TH "TeleportKey" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TeleportKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TeleportKey\&.hpp>\fP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBTeleportKey\fP ()"
.br
.ti -1c
.RI "\fB~TeleportKey\fP ()"
.br
.ti -1c
.RI "virtual void \fBonCollisionEnter\fP (\fBCollision\fP const &collision) const override"
.br
.RI "émit quand il entre en contacte avec un autre élément "
.ti -1c
.RI "virtual void \fBupdate\fP () override"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB10\fP du fichier \fBTeleportKey\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "TeleportKey::TeleportKey ()"

.PP
Définition à la ligne \fB8\fP du fichier \fBTeleportKey\&.cpp\fP\&.
.SS "TeleportKey::~TeleportKey ()"

.PP
Définition à la ligne \fB14\fP du fichier \fBTeleportKey\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void TeleportKey::onCollisionEnter (\fBCollision\fP const & collision) const\fC [override]\fP, \fC [virtual]\fP"

.PP
émit quand il entre en contacte avec un autre élément 
.PP
\fBParamètres\fP
.RS 4
\fIcollision\fP 
.RE
.PP

.PP
Implémente \fBItem\fP\&.
.PP
Définition à la ligne \fB19\fP du fichier \fBTeleportKey\&.cpp\fP\&.
.SS "void TeleportKey::update ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBItem\fP\&.
.PP
Définition à la ligne \fB24\fP du fichier \fBTeleportKey\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
