.TH "C:/programs_sc/CIC/MITST06/jeu/src/Utility/Types.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/Utility/Types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef std::uint8_t \fBuchar\fP"
.br
.ti -1c
.RI "typedef std::uint16_t \fBushort\fP"
.br
.ti -1c
.RI "typedef std::uint32_t \fBuint\fP"
.br
.ti -1c
.RI "typedef std::uint64_t \fBullong\fP"
.br
.ti -1c
.RI "typedef std::int64_t \fBllong\fP"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef std::int64_t \fBllong\fP"

.PP
Définition à la ligne \fB11\fP du fichier \fBTypes\&.hpp\fP\&.
.SS "typedef std::uint8_t \fBuchar\fP"

.PP
Définition à la ligne \fB6\fP du fichier \fBTypes\&.hpp\fP\&.
.SS "typedef std::uint32_t \fBuint\fP"

.PP
Définition à la ligne \fB8\fP du fichier \fBTypes\&.hpp\fP\&.
.SS "typedef std::uint64_t \fBullong\fP"

.PP
Définition à la ligne \fB9\fP du fichier \fBTypes\&.hpp\fP\&.
.SS "typedef std::uint16_t \fBushort\fP"

.PP
Définition à la ligne \fB7\fP du fichier \fBTypes\&.hpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
