.TH "util" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIPlatform\fP"
.br
.ti -1c
.RI "struct \fBLinuxPlatform\fP"
.br
.ti -1c
.RI "struct \fBMacOSPlatform\fP"
.br
.ti -1c
.RI "struct \fBWindowsPlatform\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
