.TH "util::WindowsPlatform" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::WindowsPlatform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WindowsPlatform\&.hpp>\fP
.PP
Est dérivée de \fButil::IPlatform\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBWindowsPlatform\fP ()"
.br
.ti -1c
.RI "void \fBsetIcon\fP (const sf::WindowHandle &inHandle) final"
.br
.ti -1c
.RI "void \fBtoggleFullscreen\fP (const sf::WindowHandle &inHandle, const sf::Uint32 inStyle, const bool inWindowed, const sf::Vector2u &inResolution) final"
.br
.ti -1c
.RI "float \fBgetScreenScalingFactor\fP (const sf::WindowHandle &inHandle) final"
.br
.ti -1c
.RI "int \fBgetRefreshRate\fP (const sf::WindowHandle &inHandle) final"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne \fB10\fP du fichier \fBWindowsPlatform\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "util::WindowsPlatform::WindowsPlatform ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "int util::WindowsPlatform::getRefreshRate (const sf::WindowHandle & inHandle)\fC [final]\fP, \fC [virtual]\fP"

.PP
Implémente \fButil::IPlatform\fP\&.
.SS "float util::WindowsPlatform::getScreenScalingFactor (const sf::WindowHandle & inHandle)\fC [final]\fP, \fC [virtual]\fP"

.PP
Implémente \fButil::IPlatform\fP\&.
.SS "void util::WindowsPlatform::setIcon (const sf::WindowHandle & inHandle)\fC [final]\fP, \fC [virtual]\fP"

.PP
Implémente \fButil::IPlatform\fP\&.
.SS "void util::WindowsPlatform::toggleFullscreen (const sf::WindowHandle & inHandle, const sf::Uint32 inStyle, const bool inWindowed, const sf::Vector2u & inResolution)\fC [final]\fP, \fC [virtual]\fP"

.PP
Implémente \fButil::IPlatform\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
