.TH "C:/programs_sc/CIC/MITST06/jeu/src/include/utils.hpp" 3 "Samedi 30 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/programs_sc/CIC/MITST06/jeu/src/include/utils.hpp
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "bool \fBisBetween\fP (float a, float min, float max)"
.br
.RI "Inclusif (strictement) "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "bool isBetween (float a, float min, float max)"

.PP
Inclusif (strictement) 
.PP
\fBParamètres\fP
.RS 4
\fIa\fP 
.br
\fImin\fP 
.br
\fImax\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
true 
.PP
false 
.RE
.PP

.PP
Définition à la ligne \fB3\fP du fichier \fButils\&.cpp\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
