.TH "Vial" 3 "Jeudi 28 Juillet 2022" "Jeu POA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vial\&.hpp>\fP
.PP
Est dérivée de \fBItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBVial\fP (\fBItemsCategories\fP \fBcategorie\fP)"
.br
.ti -1c
.RI "\fB~Vial\fP ()"
.br
.ti -1c
.RI "virtual void \fBonCollisionEnter\fP (\fBCollision\fP const &collision) const override"
.br
.RI "émit quand il entre en contacte avec un autre élément "
.ti -1c
.RI "virtual void \fBupdate\fP () override"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne \fB15\fP du fichier \fBVial\&.hpp\fP\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Vial::Vial (\fBItemsCategories\fP categorie)"

.PP
Définition à la ligne \fB9\fP du fichier \fBVial\&.cpp\fP\&.
.SS "Vial::~Vial ()"

.PP
Définition à la ligne \fB52\fP du fichier \fBVial\&.cpp\fP\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Vial::onCollisionEnter (\fBCollision\fP const & collision) const\fC [override]\fP, \fC [virtual]\fP"

.PP
émit quand il entre en contacte avec un autre élément 
.PP
\fBParamètres\fP
.RS 4
\fIcollision\fP 
.RE
.PP

.PP
Implémente \fBItem\fP\&.
.PP
Définition à la ligne \fB57\fP du fichier \fBVial\&.cpp\fP\&.
.SS "void Vial::update ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implémente \fBItem\fP\&.
.PP
Définition à la ligne \fB62\fP du fichier \fBVial\&.cpp\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu POA à partir du code source\&.
